# Generated by Django 3.1 on 2023-11-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231119_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/user_avatar.png', null=True, upload_to='userprofile,'),
        ),
    ]
