# Generated by Django 3.1 on 2023-11-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variation'),
        ('orders', '0002_auto_20231104_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='variation',
        ),
        migrations.AddField(
            model_name='productorder',
            name='variation',
            field=models.ManyToManyField(blank=True, to='products.Variation'),
        ),
    ]
