# Generated by Django 3.1 on 2023-11-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20231104_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='variation',
            new_name='variations',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
