# Generated by Django 3.1 on 2023-11-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimagegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagegallery',
            options={},
        ),
        migrations.RenameField(
            model_name='productimagegallery',
            old_name='products',
            new_name='product',
        ),
    ]
