# Generated by Django 3.1 on 2023-11-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231118_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagegallery',
            options={'verbose_name': 'productimage gallery', 'verbose_name_plural': 'product image gallery'},
        ),
    ]
